const TracksTypes = {
    FETCH_TRACKS_START: 'FETCH_TRACKS_START',
    SET_TRACKS_SUCCESS: 'SET_TRACKS_SUCCESS',
    SET_TRACKS_FAILURE: 'SET_TRACKS_FAILURE',
    FETCH_A_TRACK_START: 'FETCH_A_TRACK_START',
    SET_A_TRACK_SUCCESS: 'SET_A_TRACK_SUCCESS',
    FETCH_ARTIST_START: 'FETCH_ARTIST_START',
    SET_ARTIST_SUCCESS: 'SET_ARTIST_SUCCESS'
}

export default TracksTypes;